#!/bin/bash
networkCard="wlp3s0"
if [ -z "$networkCard" ];then
    echo "Set up network card"
    exit 1
fi

essid="$(iwlist "$networkCard" scan | grep ESSID | sed -e "s/ESSID://" -e "s/\ //g" -e "s/\"//g" | peco)"
if [ -z "$essid" ];then
    exit 1
fi

read -p "Wifi password: " pass
nmcli d wifi connect "$essid" password "$pass"
