#!/bin/sh
#
# Copyright 1995, by Hewlett-Packard Company
#
# The code in this file is from the book "Shell Programming
# Examples" by Bruce Blinn, published by Prentice Hall.
# This file may be copied free of charge for personal,
# non-commercial use provided that this notice appears in
# all copies of the file.  There is no warranty, either
# expressed or implied, supplied with this code.
#
# このファイルのコードはBruce Blinn著、Prentice Hall刊行の
# 「Shell Programming Examples」に掲載されていたものです。
# このファイルは、個人として営利を目的とせず利用する限り、
# 無償で複製してかまいません。その場合、複製のすべてに
# この説明文が含まれている必要があります。このコードに
# 関しては、明示的にも暗黙的にもいかなる保証も行いません。
#
# 名称
#    MkDir - ディレクトリを作成する
#
# 書式
#    MkDir directory
#
# 解説
#    これはディレクトリを作成するものである。
#    指定したディレクトリの途中のディレクトリが
#    存在していなくてもよい。
#
# リターン値
#    0    正常終了
#    >0   異常終了
#
############################################################
CMDNAME=`basename $0`
if [ $# -ne 1 ]; then
     echo "Usage: $CMDNAME directory" 1>&2
     exit 1
fi

case $1 in
     /*)  DIR=      ;;
     *)   DIR=.     ;;
esac

IFS=/
for d in $1
do
     DIR="$DIR/$d"
     if [ ! -d "$DIR" ]; then
          mkdir "$DIR"
          if [ $? -ne 0 ]; then
               exit $?
          fi
     fi
done

exit 0
