version: "3"

services:
  server:
    build: ./
    platform: linux/arm64/v8
    tty: true
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/mnt/app
    depends_on:
      - db
  db:
    image: "mariadb:10.6"
    platform: linux/arm64/v8
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_user_password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Tokyo
    tty: true
    restart: always
    ports:
      - 33306:3306
    volumes:
      - ./db:/mnt
      - db-data:/var/lib/mysql

volumes:
  db-data:
