[package]
name = "serde_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.91"
uuid = { version = "1.2.2", features = ["v4"] }