import React, { useState, useEffect } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
import styles from "../styles/Home.module.css";
import Faker from "faker";
import Fuse from "fuse.js";

const userData: string[] = [
  Faker.name.findName(),
  Faker.name.findName(),
  Faker.name.findName(),
  Faker.name.findName(),
  Faker.name.findName(),
  Faker.name.findName(),
  Faker.name.findName(),
  Faker.name.findName(),
  Faker.name.findName(),
  Faker.name.findName(),
];

const fuse: Fuse<string> = new Fuse(userData, {
  // includeScore: true,
  keys: ["name", "zipCode", "birthday"],
});

const Home = () => {
  const [filterValue, setFilterValue] = useState("");
  const [filtered, setFiltered] = useState<string[]>([]);

  useEffect(() => {
    const filtered = fuse.search(filterValue);
    console.log(filtered);
    setFiltered(filtered.map((v) => v.item));
  }, [filterValue]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Filter
        <input
          type="text"
          value={filterValue}
          onChange={(e) => {
            setFilterValue(e.target.value);
          }}
        />
        {userData.map((name) => (
          <div key={name}>
            <p
              className={filtered.includes(name) ? styles.bold : styles.grayOut}
            >
              {name}
            </p>
          </div>
        ))}
      </main>
    </div>
  );
};

const AvoidSSRComponent = dynamic(() => Promise.resolve(Home), { ssr: false });

export default AvoidSSRComponent;
