services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    tty: true
    restart: always
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"
    ports:
      - "5432:5432"
