name = "CsvExample"
uuid = "e9b42fb2-6ba5-47ed-b32e-33bdacfa40f8"
authors = ["mkanenobu <mitsuru.kanenobu@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
