version: "3"

services:
  mariadb:
    image: "mariadb:10.7"
    container_name: mariadb
    tty: true
    restart: always
    environment:
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "password"
      MARIADB_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
