version: "3"

services:
  mongo:
    image: "mongo:4"
    container_name: mongo
    tty: true
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/db:/data/db

  mongo-express:
    image: "mongo-express:0.54"
    ports:
      - "27018:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGODB_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGODB_PASSWORD}"
    depends_on:
      - mongo
