/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting(String name) {
        return String.format("Hello %s!", name);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting("World"));
    }
}
